on:
  push:
    branches:
      - master 




jobs:
  build:
    runs-on: ubunto-latest


    steps: 
      - name: 'Testing Github action' 
         run: pwd
       

      - name: 'Testing Printing' 
         run: echo esraa

  
